name: 'Deploy Ghost Content'
description: 'Deploy content to your Ghost site'
branding:
  icon: 'cloud-lightning'
  color: 'gray-dark'
inputs:
  api-url:
    description: 'Ghost Admin API Url'
    required: true
  api-key:
    description: 'Ghost Admin API Key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
